import { ExternalLink } from "lucide-react";
import { NexusPanel } from "../components/NexusPanel";
import type { AppSettings, Links, ManagedLibraryInfo, NexusAccount, NexusStatus, ToolInfo } from "../types";

interface Props {
  settings: AppSettings; retoc: ToolInfo; sevenZip: ToolInfo | null; managedLibrary: ManagedLibraryInfo | null; movingLibrary: boolean; onChange: (settings: AppSettings) => void;
  onSave: () => void; onPickGame: () => void; onPickExecutable: () => void; onPickRetoc: () => void; onPickSevenZip: () => void;
  onMoveLibrary: () => void; onUseDefaultLibrary: () => void; onOpenLibrary: () => void; onOpenLogs: () => void; onOpenData: () => void;
  links: Links; onOpenLink: (url: string) => void;
  nexus: NexusStatus | null; nexusAccount: NexusAccount | null;
  onSaveNexusKey: (key: string) => Promise<void>;
  onClearNexusKey: () => Promise<void>;
  onToggleNxmHandler: (enabled: boolean) => Promise<void>;
  onSetAutoUpdateCheck: (enabled: boolean) => Promise<void>;
}

export function SettingsPage({ settings, retoc, sevenZip, managedLibrary, movingLibrary, onChange, onSave, onPickGame, onPickExecutable, onPickRetoc, onPickSevenZip, onMoveLibrary, onUseDefaultLibrary, onOpenLibrary, onOpenLogs, onOpenData, links, onOpenLink, nexus, nexusAccount, onSaveNexusKey, onClearNexusKey, onToggleNxmHandler, onSetAutoUpdateCheck }: Props) {
  return <div className="page"><header className="page-header"><div><p className="eyebrow">APPLICATION</p><h1>Settings</h1><p className="muted">Local-only preferences. Zero Mod Manager has no telemetry or account.</p></div><button className="primary" onClick={onSave}>Save settings</button></header>
    <section className="settings-sections"><article className="panel"><h2>Game installation</h2><p>Automatic Steam discovery is preferred. Set a manual location if the game is in an unusual library.</p><label>Game directory<div className="input-action"><input readOnly value={settings.gamePath ?? "Automatic detection"} /><button onClick={onPickGame}>Browse</button></div></label><label>Game launch executable or launcher<div className="input-action"><input readOnly value={settings.customExecutablePath ?? "Steam default"} /><button onClick={onPickExecutable}>Browse</button>{settings.customExecutablePath && <button onClick={() => onChange({ ...settings, customExecutablePath: null })}>Use Steam</button>}</div></label><small>When set, Launch game starts this file from its containing folder. Command-line arguments are not added.</small></article>
      <article className="panel"><h2>retoc container tool</h2><p>Version 0.1.5 is bundled in release builds and discovered locally in development.</p><label>retoc executable<div className="input-action"><input readOnly value={settings.retocPath ?? retoc.path ?? "Not found"} /><button onClick={onPickRetoc}>Browse</button></div></label><small className={retoc.found ? "success-text" : "warn-text"}>{retoc.found ? `Detected ${retoc.version ?? "retoc"}` : "Required to validate IoStore mods"}</small></article>
      <article className="panel"><h2>Archive tool</h2><p>ZIP archives are read directly. Reading a <code>.7z</code> or <code>.rar</code> archive needs the 7-Zip command-line tool, which its installer does not add to <code>PATH</code>. The manager looks in the usual install folders on its own; set the path here if yours lives somewhere else.</p><label>7z executable<div className="input-action"><input readOnly value={settings.sevenZipPath ?? sevenZip?.path ?? "Not found"} /><button onClick={onPickSevenZip}>Browse</button>{settings.sevenZipPath && <button onClick={() => onChange({ ...settings, sevenZipPath: null })}>Use automatic</button>}</div></label><small className={sevenZip?.found ? "success-text" : "warn-text"}>{sevenZip?.found ? `Detected ${sevenZip.version ?? "7-Zip"}` : "Not found — .7z and .rar archives cannot be opened until this is set. Extract such an archive yourself and install the folder instead."}</small></article>
      <article className="panel"><h2>Managed mod library</h2><p>Source copies, checksums, and backups live here. Deployed mod files still go to the game folder.</p><label>Library folder<div className="input-action"><input readOnly value={managedLibrary?.path ?? "Loading…"} /><button disabled={movingLibrary || !managedLibrary} onClick={onMoveLibrary}>{movingLibrary ? "Moving…" : "Move…"}</button></div></label><small>The destination must be empty. Files are copied and verified before the manager switches locations.</small><div className="settings-actions"><button disabled={!managedLibrary || movingLibrary} onClick={onOpenLibrary}>Open library</button>{managedLibrary && !managedLibrary.isDefault && <button disabled={movingLibrary} onClick={onUseDefaultLibrary}>Use Local AppData</button>}</div></article>
      <article className="panel"><h2>Privacy and display</h2><label>Log detail<select value={settings.logLevel} onChange={e => onChange({ ...settings, logLevel: e.target.value as AppSettings["logLevel"] })}><option value="normal">Normal — sanitized</option><option value="verbose">Verbose</option><option value="developer">Developer — may expose game paths</option></select></label><label className="check"><input type="checkbox" checked={settings.advancedPackageNames} onChange={e => onChange({ ...settings, advancedPackageNames: e.target.checked })} />Allow raw package names in advanced views</label><label className="check"><input type="checkbox" checked={settings.reducedMotion} onChange={e => onChange({ ...settings, reducedMotion: e.target.checked })} />Reduce interface motion</label><div className="settings-actions"><button onClick={onOpenLogs}>Open logs folder</button><button onClick={onOpenData}>Open app data</button></div></article>
      <NexusPanel status={nexus} account={nexusAccount} onSaveKey={onSaveNexusKey} onClearKey={onClearNexusKey} onToggleHandler={onToggleNxmHandler} onOpenLink={onOpenLink} autoCheck={settings.nexusAutoUpdateCheck} onAutoCheckChange={onSetAutoUpdateCheck} />
      <article className="panel"><h2>Community resources</h2><p>Links open in your browser. Zero Mod Manager never downloads anything by itself.</p><div className="settings-actions"><button onClick={() => onOpenLink(links.nexusGame)}><ExternalLink aria-hidden size={16} />Zero Company mods on Nexus</button><button onClick={() => onOpenLink(links.ue4ssDownload)}><ExternalLink aria-hidden size={16} />UE4SS for Zero Company</button>{links.project && <button onClick={() => onOpenLink(links.project)}><ExternalLink aria-hidden size={16} />Project repository</button>}</div></article>
    </section>
  </div>;
}
