import { ExternalLink } from "lucide-react";
import type { AppSettings, Links, ManagedLibraryInfo, ToolInfo } from "../types";

interface Props {
  settings: AppSettings; sevenZip: ToolInfo | null; managedLibrary: ManagedLibraryInfo | null; movingLibrary: boolean; onChange: (settings: AppSettings) => void;
  onSave: () => void; onPickGame: () => void; onPickExecutable: () => void; onPickSevenZip: () => void;
  onMoveLibrary: () => void; onUseDefaultLibrary: () => void; onOpenLibrary: () => void; onOpenLogs: () => void; onOpenData: () => void;
  links: Links; onOpenLink: (url: string) => void;
}

export function SettingsPage({ settings, sevenZip, managedLibrary, movingLibrary, onChange, onSave, onPickGame, onPickExecutable, onPickSevenZip, onMoveLibrary, onUseDefaultLibrary, onOpenLibrary, onOpenLogs, onOpenData, links, onOpenLink }: Props) {
  return <div className="page"><header className="page-header"><div><h1>Settings</h1></div><button className="primary" onClick={onSave}>Save settings</button></header>
    <section className="settings-sections"><article className="panel"><h2>Game installation</h2><label>Game directory<div className="input-action"><input readOnly value={settings.gamePath ?? "Automatic detection"} /><button onClick={onPickGame}>Browse</button></div></label><label>Game launch executable or launcher<div className="input-action"><input readOnly value={settings.customExecutablePath ?? "Steam default"} /><button onClick={onPickExecutable}>Browse</button>{settings.customExecutablePath && <button onClick={() => onChange({ ...settings, customExecutablePath: null })}>Use Steam</button>}</div></label><small>Optional override. Command-line arguments are not supported.</small></article>
      <article className="panel"><h2>Archive tool</h2><p>ZIP works without extra tools. For 7z/RAR, use 7-Zip or extract the archive and install its folder.</p><label>7z executable<div className="input-action"><input readOnly value={settings.sevenZipPath ?? sevenZip?.path ?? "Not found"} /><button onClick={onPickSevenZip}>Browse</button>{settings.sevenZipPath && <button onClick={() => onChange({ ...settings, sevenZipPath: null })}>Use automatic</button>}</div></label><small className={sevenZip?.found ? "success-text" : "warn-text"}>{sevenZip?.found ? `Detected ${sevenZip.version ?? "7-Zip"}` : "Not found. Install an extracted folder instead."}</small></article>
      <article className="panel"><h2>Managed mod library</h2><p>Source copies, checksums, and backups live here. Deployed mod files still go to the game folder.</p><label>Library folder<div className="input-action"><input readOnly value={managedLibrary?.path ?? "Loading…"} /><button disabled={movingLibrary || !managedLibrary} onClick={onMoveLibrary}>{movingLibrary ? "Moving…" : "Move…"}</button></div></label><small>The destination must be empty. Files are copied and verified before the manager switches locations.</small><div className="settings-actions"><button disabled={!managedLibrary || movingLibrary} onClick={onOpenLibrary}>Open library</button>{managedLibrary && !managedLibrary.isDefault && <button disabled={movingLibrary} onClick={onUseDefaultLibrary}>Use Local AppData</button>}</div></article>
      <article className="panel"><h2>Privacy and display</h2><label>Log detail<select value={settings.logLevel} onChange={e => onChange({ ...settings, logLevel: e.target.value as AppSettings["logLevel"] })}><option value="normal">Normal — sanitized</option><option value="verbose">Verbose</option><option value="developer">Developer — may expose game paths</option></select></label><label className="check"><input type="checkbox" checked={settings.advancedPackageNames} onChange={e => onChange({ ...settings, advancedPackageNames: e.target.checked })} />Allow raw package names in advanced views</label><label className="check"><input type="checkbox" checked={settings.reducedMotion} onChange={e => onChange({ ...settings, reducedMotion: e.target.checked })} />Reduce interface motion</label><div className="settings-actions"><button onClick={onOpenLogs}>Open logs folder</button><button onClick={onOpenData}>Open app data</button></div></article>
      <article className="panel"><h2>Community resources</h2><div className="settings-actions"><button onClick={() => onOpenLink(links.nexusGame)}><ExternalLink aria-hidden size={16} />Zero Company mods on Nexus</button><button onClick={() => onOpenLink(links.ue4ssDownload)}><ExternalLink aria-hidden size={16} />UE4SS for Zero Company</button>{links.project && <button onClick={() => onOpenLink(links.project)}><ExternalLink aria-hidden size={16} />Project repository</button>}</div></article>
    </section>
  </div>;
}
